### PR TITLE
Add the Lupa crawler to README.md

### PR DESCRIPTION
**Pull request by bortzmeyer**
Add the Lupa crawler

### CODE REVIEW

**Comment by kr1sp1n** [comment]
@bortzmeyer There are some minor conflicts in your last PRs. Please resolve them and push your changes. Thanks 🙏

**Comment by bortzmeyer** [comment]
On Mon, Feb 01, 2021 at 11:47:32PM -0800,
 Krispin Schulz <notifications@github.com> wrote 
 a message of 59 lines which said:

> @bortzmeyer There are some minor conflicts in your last PRs. Please
> resolve them and push your changes.

I don't see the conflict. Github tells me the PR can be merged.

> Able to merge. These branches can be automatically merged.

**Comment by kr1sp1n** [comment]
@bortzmeyer Sorry, but in this PR I read `This branch cannot be rebased due to conflicts`. So please solve the conflicts and then I would love to merge 😉

**Comment by bortzmeyer** [comment]
Replaced by PR #42

**Pull request closed without merging**
