### PR TITLE
split out pure gemtext converters into their own list

### PR DESCRIPTION
**Pull request by mk270**

### CODE REVIEW

**Comment by kr1sp1n** [comment]
@mk270 After merging other PRs there are some conflicts now. Please resolve conflicts. Thanks! 🙏

**Comment by mk270** [comment]
Ok - that was my fault. I've pushed an additional commit which resolves the merge conflict.

**Comment by kr1sp1n** [comment]
Mmmh, still conficts. Can you check again? Thank you!

**Comment by mk270** [comment]
What are you doing to attempt to merge it? (above, it says "This branch has no conflicts with the base branch")This branch has no conflicts with the base branch

**Comment by kr1sp1n** [comment]
@mk270 For me it says here on github: "This branch cannot be rebased due to conflicts".
Strange, maybe a bug. I could resolve it by myself, if you like.

**Comment by mk270** [comment]
@kr1sp1n yes but what are you actually doing in order to trigger this? I presume you're pressing some button on github, rather than doing something on the commandline on your own computer? Why is it talking about rebasing rather than merging?

**Comment by mk270** [comment]
Having had a look at the UI on github for a merge request on one of my own projects, it seems that there is a green button saying "Merge pull request", which has a dropdown option offering "Squash and merge" and "Rebase and merge". Do you see the same thing, and if so, which of these options are you using?

**Comment by kr1sp1n** [comment]
@mk270 Hi, I use "Rebase and merge" button, but as long as there are conflicts it is not possible to merge.

**Comment by mk270** [comment]
Ok, well, please try merging, that is use the "Create a merge commit" option, rather than "rebase and merge".

On the interface that I see on github.com, this is the default.

**Comment by kr1sp1n** [comment]
@mk270 Thanks for the hint 😉 I never did it this way. Have a nice day! 👋

**Comment by mk270** [comment]
thanks for sorting this out!

**Pull request merged**
