### PR TITLE
note tool for conversion to LaTeX / PDF

### PR DESCRIPTION
**Pull request by mk270**

### CODE REVIEW

**Comment by kr1sp1n** [comment]
@mk270 Thank you again 😉

**Comment by kr1sp1n** [comment]
@mk270 Why is it confusing? What tool do you use to render the graph? Can you please upload a snapshot of it so I could understand what do you mean? Thanks in advance!

**Comment by mk270** [comment]
The tool is built into github, and you can navigate to it at "Insights | Network" from any repo.

This repo: https://github.com/kr1sp1n/awesome-gemini/network

Another repo, showing merges: https://github.com/mk270/whitakers-words/network

But `git log --graph` produces the same sort of thing, rotated through 90 degrees. The issue here is that the graph view makes it obvious which branches are unmerged, except in this one `awesome-gemini` repo.

**Comment by kr1sp1n** [comment]
@mk270 Mmmh, strange. I just merge PRs into the `master` branch. And nothing else is configured differently. Do you have any idea how to solve this behaviour?

**Comment by mk270** [comment]
thank you. I'll look into it!

**Pull request merged**
